-- ============================================================
-- Agent-Memory: Schema
-- ArcadeDB multi-model: personal assistant memory system
-- ============================================================

-- Vertex types (8)

CREATE VERTEX TYPE JournalEntry IF NOT EXISTS
CREATE PROPERTY JournalEntry.date DATE
CREATE PROPERTY JournalEntry.content STRING
CREATE PROPERTY JournalEntry.dayName STRING
CREATE PROPERTY JournalEntry.weekNumber INTEGER
CREATE PROPERTY JournalEntry.emotionalIntensity STRING

CREATE VERTEX TYPE Person IF NOT EXISTS
CREATE PROPERTY Person.name STRING
CREATE PROPERTY Person.function STRING
CREATE PROPERTY Person.team STRING

CREATE VERTEX TYPE Project IF NOT EXISTS
CREATE PROPERTY Project.name STRING
CREATE PROPERTY Project.type STRING
CREATE PROPERTY Project.status STRING

CREATE VERTEX TYPE Task IF NOT EXISTS
CREATE PROPERTY Task.content STRING
CREATE PROPERTY Task.state STRING
CREATE PROPERTY Task.deadline DATE
CREATE PROPERTY Task.createdAt DATETIME

CREATE VERTEX TYPE Note IF NOT EXISTS
CREATE PROPERTY Note.content STRING
CREATE PROPERTY Note.type STRING
CREATE PROPERTY Note.createdAt DATETIME

CREATE VERTEX TYPE AudioTranscript IF NOT EXISTS
CREATE PROPERTY AudioTranscript.title STRING
CREATE PROPERTY AudioTranscript.summary STRING
CREATE PROPERTY AudioTranscript.recordedAt DATE

CREATE VERTEX TYPE ContentTag IF NOT EXISTS
CREATE PROPERTY ContentTag.name STRING
CREATE PROPERTY ContentTag.category STRING

CREATE VERTEX TYPE AgentPersona IF NOT EXISTS
CREATE PROPERTY AgentPersona.name STRING
CREATE PROPERTY AgentPersona.framework STRING
CREATE PROPERTY AgentPersona.interactionStyle STRING

-- Edge types (6)

CREATE EDGE TYPE MENTIONS IF NOT EXISTS
CREATE EDGE TYPE HAS_TAG IF NOT EXISTS
CREATE EDGE TYPE BELONGS_TO IF NOT EXISTS
CREATE EDGE TYPE COLLABORATES_ON IF NOT EXISTS
CREATE EDGE TYPE REFERENCES IF NOT EXISTS
CREATE EDGE TYPE RECORDED_DURING IF NOT EXISTS

-- Document types (2)

CREATE DOCUMENT TYPE UserProfile IF NOT EXISTS
CREATE PROPERTY UserProfile.name STRING
CREATE PROPERTY UserProfile.role STRING
CREATE PROPERTY UserProfile.bigFiveOpenness INTEGER
CREATE PROPERTY UserProfile.bigFiveConscientiousness INTEGER
CREATE PROPERTY UserProfile.bigFiveExtraversion INTEGER
CREATE PROPERTY UserProfile.bigFiveAgreeableness INTEGER
CREATE PROPERTY UserProfile.bigFiveNeuroticism INTEGER
CREATE PROPERTY UserProfile.workingStyleSummary STRING

CREATE DOCUMENT TYPE CoachingSession IF NOT EXISTS
CREATE PROPERTY CoachingSession.sessionId STRING
CREATE PROPERTY CoachingSession.date DATE
CREATE PROPERTY CoachingSession.agentPersona STRING
CREATE PROPERTY CoachingSession.questions LIST
CREATE PROPERTY CoachingSession.insights LIST

-- Indexes

CREATE INDEX IF NOT EXISTS ON JournalEntry (date) NOTUNIQUE
CREATE INDEX IF NOT EXISTS ON JournalEntry (weekNumber) NOTUNIQUE
CREATE INDEX IF NOT EXISTS ON Person (name) UNIQUE
CREATE INDEX IF NOT EXISTS ON Project (name) UNIQUE
CREATE INDEX IF NOT EXISTS ON ContentTag (name) UNIQUE
CREATE INDEX IF NOT EXISTS ON CoachingSession (agentPersona) NOTUNIQUE
CREATE INDEX IF NOT EXISTS ON JournalEntry (content) FULL_TEXT
CREATE INDEX IF NOT EXISTS ON Note (content) FULL_TEXT
